// Sample data: the real grill-with-ui design session of 2026-09-06, lightly compressed.
const SESSION = {
  topic: "grill-with-ui skill",
  project: "~/Projects/grill-with-ui",
  doc: "docs/design.md",
  agent: { status: "waiting", since: "22:41" },
  terms: [
    { term: "Round", def: "One agent turn's worth of new questions: the current frontier.", avoid: ["batch", "wave"] },
    { term: "Frontier", def: "Questions whose prerequisites are all settled and can be asked now.", avoid: ["queue", "next up"] },
    { term: "Send", def: "One press of Send to Agent: every staged action shipped as a single event.", avoid: ["submit", "reply"] },
    { term: "Durable decision", def: "Hard to reverse, surprising without context, a real trade-off. Goes under Locked decisions.", avoid: ["ADR", "big decision"] },
  ],
  rounds: [
    { n: 1, ids: ["q1"] }, { n: 2, ids: ["q2"] }, { n: 3, ids: ["q3", "q4"] },
    { n: 4, ids: ["q5", "q6", "q7"] }, { n: 5, ids: ["q8", "q9"] }, { n: 6, ids: ["q10", "q11"] },
    { n: 7, ids: ["q12", "q13", "q14"] }, { n: 8, ids: ["q15", "q16", "q17"] },
  ],
  questions: {
    q1: { id: "q1", round: 1, title: "UI surface", deps: [],
      body: "What is the UI surface, and how does it talk to the running session? This is the root decision; state format, threads and resume all hang off it.",
      options: [
        { k: "A", text: "Local browser app. A tiny bundled server serves a page and reads/writes one state file per session. Terminal stays a parallel input." },
        { k: "B", text: "Read-only side panel. Claude re-renders an HTML summary each turn; you still answer in the terminal by number." },
        { k: "C", text: "MCP app panel. Only if Claude Code renders it. Heavier to build and install." },
        { k: "D", text: "Terminal TUI. Doesn't solve scrollback. Listed to rule out." },
      ],
      rec: { option: "A", why: "Works in any terminal today, nothing to install, and the file protocol is agent-neutral so a Codex version is packaging, not a rewrite." },
      status: "answered", answer: { kind: "accept", option: "A", text: "A is exactly what I was thinking" }, durable: true, thread: [] },
    q2: { id: "q2", round: 2, title: "Transport", deps: ["q1"],
      body: "How does a browser answer reach the running Claude session? Docs check: Monitor wakes an idle session; a background shell exiting does not; Channels need a launch flag.",
      options: [
        { k: "A", text: "Persistent Monitor on the server's WebSocket. Every browser action is one event and one Claude turn." },
        { k: "B", text: "Claude Code Channels. Officially blessed, but needs a startup flag and a plugin." },
        { k: "C", text: "Manual nudge: answer in the browser, type 'go' in the terminal." },
      ],
      rec: { option: "A", why: "No startup flags, works from inside the skill. Live test fired while idle: verified." },
      status: "answered", answer: { kind: "text", text: "Simpler: the web app writes to a local JSON and the agent has a file-change watcher on it." },
      durable: true,
      thread: [
        { who: "agent", text: "Yes, and simpler than what I proposed. Refinement: two files, not one. state.json written only by the agent; events.jsonl appended only by the web app, watched with plain tail -F." },
      ] },
    q3: { id: "q3", round: 3, title: "Questions per turn", deps: ["q2"],
      body: "When Claude replies to a batch, how many new questions does it post on top of the thread replies?",
      options: [
        { k: "A", text: "Exactly one new primary question per turn. Keeps 'resolve dependencies one by one'." },
        { k: "B", text: "Up to a few new questions when they're independent. Fewer round trips; recommendations can go stale." },
      ],
      rec: { option: "A", why: "You already batch on your side; keeping Claude to one at a time is what makes recommendations trustworthy." },
      status: "answered", answer: { kind: "option", option: "B", text: "" }, durable: false, thread: [] },
    q4: { id: "q4", round: 3, title: "Thread context", deps: ["q1"],
      body: "What does 'chat more about a question without losing context' mean mechanically?",
      options: [
        { k: "A", text: "One Claude session; threads are labeled messages. Nothing is separate under the hood." },
        { k: "B", text: "A subagent per thread, seeded with a summary. Isolation, but loses exactly the context you want." },
      ],
      rec: { option: "A", why: "The thing you're missing is navigation, not isolation. The page provides that." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: true, thread: [] },
    q5: { id: "q5", round: 4, title: "Question card shape", deps: ["q4"],
      body: "What does a question look like on the page, and how do you answer it? This fixes the state schema.",
      options: [
        { k: "A", text: "Structured card: title, body, lettered options, a recommendation pointing at one, a rationale. Answer by option, Accept, or free text. Thread box separate." },
        { k: "B", text: "Free text everywhere. Simpler schema, no one-click accept." },
      ],
      rec: { option: "A", why: "Grilling already produces lettered options and a named recommendation, so structure costs nothing." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: false, thread: [] },
    q6: { id: "q6", round: 4, title: "Terminal role", deps: ["q1"],
      body: "What does the terminal do while a grill runs in the page?",
      options: [
        { k: "A", text: "One-line status per turn, plus the URL. Terminal typing still works and is recorded into state." },
        { k: "B", text: "Terminal goes silent. Launch only." },
        { k: "C", text: "Terminal mirrors the full text. Defeats the purpose." },
      ],
      rec: { option: "A", why: "Same scrollback cost as silence, and it gives you the 'Claude is waiting' signal where you're already looking." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: false, thread: [] },
    q7: { id: "q7", round: 4, title: "Server lifecycle", deps: ["q2"],
      body: "Who starts and stops the local server, and how do we guarantee it dies? Orphaned processes have bitten this machine before.",
      options: [
        { k: "A", text: "The server is the monitor. It lives exactly as long as the monitor: killed at session end or on Finish. Nothing to orphan." },
        { k: "B", text: "Server in the background, separate tail watcher. Needs its own shutdown story; every option is a way to leak." },
      ],
      rec: { option: "A", why: "Same file-based design, with writer and watcher collapsed into one process the harness already manages." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: true, thread: [] },
    q8: { id: "q8", round: 5, title: "Finish + deliverable", deps: ["q5"],
      body: "How does a grill end, and what's the deliverable? Past grills all ended as design docs.",
      options: [
        { k: "A", text: "Explicit Finish button; Claude writes a markdown decisions doc from state. Doc path asked once at start." },
        { k: "B", text: "No explicit end; the state file is the record." },
      ],
      rec: { option: "A", why: "Writing from a structured state file is more faithful than writing from a long transcript." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: false,
      thread: [
        { who: "user", text: "Can you also look up Matt Pocock's grill-with-docs skill to see what we can borrow for the docs part, and compare it to the docs we already generate?" },
        { who: "agent", text: "Fetched it. It's one line: run grilling + domain-modeling. The docs part writes a repo-wide CONTEXT.md glossary and sparse ADRs gated on hard-to-reverse, surprising, real trade-off. Your docs are the opposite shape: one exhaustive topic doc builders consume as the spec. Turned into Q9." },
      ] },
    q9: { id: "q9", round: 5, title: "What Finish writes", deps: ["q8"],
      body: "Your exhaustive topic doc, Matt's sparse ADRs and glossary, or both?",
      options: [
        { k: "A", text: "Your design doc, with two borrows: a per-decision durable flag (Locked vs Routine sections) and a Terms section with Avoid lists." },
        { k: "B", text: "Your design doc plus ADRs in docs/adr and a root CONTEXT.md. Two places to keep in sync." },
        { k: "C", text: "Matt's files only. Rejected: builders need the exhaustive doc." },
      ],
      rec: { option: "A", why: "The durable flag and the terms section fix two real problems; repo-wide files can be an opt-in flag later." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: true, thread: [] },
    q10: { id: "q10", round: 6, title: "State location + resume", deps: ["q7"],
      body: "Where does session state live, and how does resume work? Several worktrees per project here.",
      options: [
        { k: "A", text: "Per-session folder under home, keyed by git common root (working directory when not in git). Resume lists unfinished sessions for the project." },
        { k: "B", text: "Inside the repo, gitignored. Lives in one worktree; ws reset wipes it." },
      ],
      rec: { option: "A", why: "Worktree independence decides it here; for adopters it also means zero repo changes." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: true,
      thread: [
        { who: "user", text: "Hm, what would be easier for other people to adopt?" },
        { who: "agent", text: "Outside the repo, by a wider margin: zero repo changes, one mental model, works outside git, resume is discoverable anyway. Only loss: sessions don't travel with a clone, which is a non-goal." },
      ] },
    q11: { id: "q11", round: 6, title: "Stack", deps: ["q10"],
      body: "What is the server and page built with? Must run the moment the skill is installed.",
      options: [
        { k: "A", text: "Plain Node, no dependencies, no build step. One server script, one self-contained HTML page." },
        { k: "B", text: "Bun. Nicer API, not on most machines." },
        { k: "C", text: "React with a build step." },
      ],
      rec: { option: "A", why: "Claude Code requires Node, so every adopter has it. Polish comes from CSS, not the framework." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: false, thread: [] },
    q12: { id: "q12", round: 7, title: "Relation to grilling skills", deps: ["q9"],
      body: "How does grill-with-ui relate to the grilling and grill-me skills you already have?",
      options: [
        { k: "A", text: "Self-contained new skill with its own interview prompt (frontier-per-round) plus the page protocol. Developed in its own repo, symlinked in." },
        { k: "B", text: "Composition, Matt-style: invoke grilling plus a protocol skill. Two skills fighting over output format." },
        { k: "C", text: "A flag on grill-me." },
      ],
      rec: { option: "A", why: "One folder, one prompt, nothing to depend on. Publishable later without extraction." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: false, thread: [] },
    q13: { id: "q13", round: 7, title: "Agent neutrality", deps: ["q11"],
      body: "Claude Code only, or agent-neutral from the start? Codex has no Monitor; Bedrock/Vertex Claude Code lacks it too.",
      options: [
        { k: "A", text: "Add a blocking wait mode to the server now: blocks in the foreground until the next Send, prints it, exits. About twenty lines." },
        { k: "B", text: "Claude Code only for v1." },
      ],
      rec: { option: "A", why: "Cheap, also the fallback for Claude Code without Monitor, keeps the no-lock-in promise." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: false, thread: [] },
    q14: { id: "q14", round: 7, title: "Build order", deps: ["q13"],
      body: "What gets built first? One assumption is unverified: the harness labels monitor events 'not user input'; the skill prompt says Send events are your answers.",
      options: [
        { k: "A", text: "Spike the wake-up path first: minimal server, one-textarea page, stub prompt with only the event rule. One real round." },
        { k: "B", text: "Build everything, then test end to end." },
      ],
      rec: { option: "A", why: "The only piece that can't be reasoned out from what we already know." },
      status: "answered", answer: { kind: "accept", option: "A" }, durable: false, thread: [] },
    q15: { id: "q15", round: 8, title: "Page visual direction", deps: ["q11"],
      body: "Three mockups are on the table. Which layout carries forward into the spike page?",
      options: [
        { k: "A", text: "Inbox: question list on the left, one detail card on the right, sticky send bar." },
        { k: "B", text: "Scroll: single column of cards grouped by round, outline rail for jumping." },
        { k: "C", text: "Tree + focus: dependency tree on the left, one focused card, thread drawer." },
      ],
      rec: { option: "A", why: "Best fit for 'go back to an earlier question' and it keeps the current question in view while you read history." },
      status: "open", answer: null, durable: false, thread: [] },
    q16: { id: "q16", round: 8, title: "Doc template sections", deps: ["q9"],
      body: "Section order for the generated design doc: Terms, Why, Locked decisions, Routine choices, Deferred, Follow-ups?",
      options: [
        { k: "A", text: "That order, with the header carrying the locked-decision count and the date." },
        { k: "B", text: "Decisions first, Terms at the end as an appendix." },
      ],
      rec: { option: "A", why: "Terms first is what makes cold re-entry work; the header count is your existing convention." },
      status: "open", answer: null, durable: false, updated: true, thread: [] },
    q17: { id: "q17", round: 8, title: "Keyboard shortcuts", deps: ["q15"],
      body: "j/k to move between questions, a/b/c to pick an option, enter to stage, cmd+enter to send?",
      options: [
        { k: "A", text: "Yes, all of them, shown in a footer hint." },
        { k: "B", text: "Defer to after the spike." },
      ],
      rec: { option: "B", why: "Zero cost to add later; not on the critical path." },
      status: "deferred", answer: null, durable: false, thread: [] },
  },
};
